// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE_Lgbsd_qzmIAX5R9Bm0gBlUXUDU6sUs',
    appId: '1:167830565516:web:b5e50f7f97e6c0c1eb01a9',
    messagingSenderId: '167830565516',
    projectId: 'al-jilani-chicken-account',
    authDomain: 'al-jilani-chicken-account.firebaseapp.com',
    storageBucket: 'al-jilani-chicken-account.appspot.com',
    measurementId: 'G-X3FN412Z0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEHNOcyZCbp27Sp56li2lk6n0yRuLdsq4',
    appId: '1:167830565516:android:575545af962e50a8eb01a9',
    messagingSenderId: '167830565516',
    projectId: 'al-jilani-chicken-account',
    storageBucket: 'al-jilani-chicken-account.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIAzGzVTgehPD1FXb_Vx2ihKiKqHWSPYw',
    appId: '1:167830565516:ios:7bd3f430ee29432feb01a9',
    messagingSenderId: '167830565516',
    projectId: 'al-jilani-chicken-account',
    storageBucket: 'al-jilani-chicken-account.appspot.com',
    iosClientId:
        '167830565516-i3b8q5cu4fdoqho18l30kd4lsklbaue5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chickenaccount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIAzGzVTgehPD1FXb_Vx2ihKiKqHWSPYw',
    appId: '1:167830565516:ios:f371baa37d3608fdeb01a9',
    messagingSenderId: '167830565516',
    projectId: 'al-jilani-chicken-account',
    storageBucket: 'al-jilani-chicken-account.appspot.com',
    iosClientId:
        '167830565516-usq9nuqv0fg6de45d58iadh74o3m7esn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chickenaccount.RunnerTests',
  );
}
